### ISSUE TITLE
[iOS][Unity] Conflict with notification

### ISSUE THREAD

**Issue by evgeny-detkov** [devtodev-analytics/unity-sdk#5]
Hello!
After calling the registration of standard notifications

```
#if UNITY_IOS
            UnityEngine.iOS.NotificationServices.RegisterForNotifications (
                UnityEngine.iOS.NotificationType.Alert |
                UnityEngine.iOS.NotificationType.Badge |
                UnityEngine.iOS.NotificationType.Sound);
#endif
```

the application closes with an error. Perhaps this is a conflict with push notifications devtodev.
I do not use push notifications devtodev.
Integrated package SDK 2.5.6
Registration of notifications is made on one of the game's tutorial steps, i.e. not since the launch itself.
In the game at this step, after the registration call, a message about the notification permission is displayed, click "Allow" - the application crashes (can close immediately or in a few seconds). Attached a screenshot from xcode.

![screen2017-10-11 17 55 47](https://user-images.githubusercontent.com/5319984/31449793-8ce3b74e-aeb0-11e7-98cb-6e9f67f39335.png)

**Comment by evgeny-detkov** [comment]
Я так понимаю, техническая поддержка есть и на русском языке?)
Надеюсь на помощь с вашей стороны.

**Comment by Skazochnij** [comment]
Добрый день, вы используете интеграцию кодом или через визуальный редактор?

**Comment by evgeny-detkov** [comment]
Интеграция через Панель инструментов Unity -> Window -> devtodev
Старых скриптов не было, интеграция " с нуля".
Unity 5.6.1f1, iOS 10+, xcode 8.3.3 / 9.0

**Comment by evgeny-detkov** [comment]
Интеграция без использования window/devtodev дает такой же результат - вылет там же.
Решили собрать пустой проект и повторить в нем - не удается повторить ошибку. Соответственно, конфликт с чем-то другим. Будем копать дальше.

**Comment by evgeny-detkov** [comment]
Выпилил devtodev SDK, по туториалу дошел до шага, где включаются нотификации - все норм.
Заново интегрировал SDK - трабл повторился, т.е. происходит вылет приложения с ошибкой, как на скрине.
Причем, если использовать включение push-нотификаций в devtodev, то запрос на разрешение уведомлений будет в самом начале при старте приложения и после клика в нативном окне вылета не происходит.
Посоветуйте, с чем может быть связана ошибка? Судя по скрину вылетает сообщение/событие что-то типа PushDidRegisterNotification (слева на скрине), если пролистать вниз, то их там порядка 20 тысяч.
Что еще можно попробовать?

**Comment by Skazochnij** [comment]
Добрый вечер. Попробуйте совсем выключить наши пуш-уведомления в окне интеграции, и удалить весь код, связанный с "DevToDev.PushManager". К сожалению нам пока не удается повторить данную проблему :(

**Comment by evgeny-detkov** [comment]
Удалось избежать ошибки следующим образом:

                DevToDev.PushManager.PushNotificationsEnabled = false;

                #if UNITY_IOS
                              NotificationServices.RegisterForNotifications(
                              UnityEngine.iOS.NotificationType.Alert |
                              UnityEngine.iOS.NotificationType.Badge |
                              UnityEngine.iOS.NotificationType.Sound, false);
                #endif

**Comment by alexey-nikitin-dteamstudio** [comment]
Hello. I have the same issue.
Unfortunately I cannot send you a test project. I'll just provide you available information.
No issues for me when:
1) Unity 2018.2.15
2) DevToDev 2.10
3) Platform: ios

Issue happens when:
1) Add firebase analytics.

Just after adding firebase analytics sdk issue starts to happen.

**Comment by kilj** [comment]
Yeah, I have the same problem. I have devtodev (but I don't use its push notifications) and Firebase in my iOS project and it immediately crashes on startup if FirebaseAppDelegateProxyEnabled for Firebase (option for method swizzling, which is necessary for Firebase proper work from Unity) is YES in info.plist. If FirebaseAppDelegateProxyEnabled will be setted to NO, app will work, but (obliviously) push notifications from firebase will not work.

So, I guess, the problem is in method swizzling. Firebase replaces some methods which are used by devtodev and devtodev can't find proper handlers and raises EXC_BAD_ACCESS.

Setting DevToDev.PushManager.PushNotificationsEnabled = false; doesn't help at all. 
I use devtodev-unity 2.12.5.
